const dummy_data = [
  {
    name: 'Task 1',
    description: 'Lorem ipsum dolor sit amet',
    dueDate: '2024-06-30',
    priority: 'Moderate',
  },
  {
    name: 'Task 2',
    description:'The graphic and typographic operators know this well in reality all the professions dealing with the universe of communication',
    dueDate: '2024-06-30',
    priority: 'High',
  },
  {
    name: 'Lorem ipsum',
    description: 'in reality all the professions dealing',
    dueDate: '2024-07-24',
    priority: 'Low',
  },
  {
    name: 'Richard McClintock',
    description:'The discovery was made by Richard McClintock , a professor of Latin at Hampden-Sydney College in Virginia',
    dueDate: '2024-07-11',
    priority: 'Low',
  },
  {
    name: 'Latin',
    description:'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium',
    dueDate: '2024-07-22',
    priority: 'High',
  },
  {
    name: 'CSS Gradient',
    description: 'CSS Gradient is a designstripe project',
    dueDate: '2024-08-27',
    priority: 'Moderate',
  },
  {
    name: ' Simplified Deployment ',
    description:'The entire course was re-recorded from scratch and was therefore completely',
    dueDate: '2024-06-07',
    priority: 'High',
  },
  {
    name: 'Smooth Updating',
    description: "It's now 100% up-to-date ",
    dueDate: '2024-06-19',
    priority: 'Moderate',
  },
  {
    name: 'Angular Schematics',
    description:'Brand-new "Essentials" sections were added, covering modern Angular',
    dueDate: '2024-06-14',
    priority: 'Moderate',
  },
  {
    name: ' Important CLI Commands',
    description: 'This course therefore once again teaches modern Angular',
    dueDate: '2024-06-28',
    priority: 'Low',
  },
  {
    name: 'Ng add',
    description:'Join the most comprehensive and bestselling Angular course on Udemy and learn all about this amazing framework from the ground up, in great depth!',
    dueDate: '2024-06-09',
    priority: 'Low',
  },
  {
    name: 'Multiple Projects',
    description:'This course starts from scratch, you neither need to know Angular 1 nor Angular 2 or any other Angular version!',
    dueDate: '2024-07-24',
    priority: 'Low',
  },
  {
    name: 'Module Introduction',
    description: 'From Setup to Deployment',
    dueDate: '2024-07-11',
    priority: 'High',
  },
  {
    name: 'Master Angular',
    description: 'Directives, Services, Forms, Http Access',
    dueDate: '2024-07-25',
    priority: 'High',
  },
  {
    name: 'Standalone components',
    description:'Absolutely fantastic tutorial series. I cannot thank you enough. The quality is first class and your presentational skills are second to none. Keep up this excellent work. You really rock!',
    dueDate: '2024-06-13',
    priority: 'Moderate',
  },
  {
    name: 'HTTP requests',
    description:'TypeScript is the main language used by the official Angular team',
    dueDate: '2024-07-08',
    priority: 'Moderate',
  },
  {
    name: 'Single-page or fullstack applications',
    description:'Angular is the next big deal. Being the successor of the overwhelmingly successful Angular.js',
    dueDate: '2024-06-09',
    priority: 'Low',
  },
  {
    name: 'CRUD Operations',
    description:'In this tutorial, I will show you crud operations in angular 17 with node js mysql.',
    dueDate: '2024-06-09',
    priority: 'Moderate',
  },
  {
    name: 'Node JS MySQL Tutorial',
    description:'	This example will help you with angular 17 crud with node js and MySQL.',
    dueDate: '2024-08-15',
    priority: 'Low',
  },
  {
    name: 'Angular 17',
    description:'Angular 17 CRUD with Node.js Express and MySQL Database enables creating, reading, updating, and deleting data in a web application.',
    dueDate: '2024-06-09',
    priority: 'Low',
  },
  {
    name: 'Why Angular?',
    description:'Angular is the next big deal. Being the successor of the overwhelmingly successful Angular.js framework it’s bound to shape the future of frontend development in a similar way.',
    dueDate: '2024-09-11',
    priority: 'Low',
  },
  {
    name: 'Angular Applications',
    description:'Angular is faster than Angular 1 and offers a much more flexible and modular development approach. After taking this course you’ll be able to fully take advantage of all those features and start developing awesome applications immediately.',
    dueDate: '2024-08-01',
    priority: 'Low',
  },
  {
    name: 'Maximilian Schwarzmüller',
    description:'	AWS certified, Professional Web Developer and Instructor Experience as (Web) Developer',
    dueDate: '2024-07-06',
    priority: 'Low',
  },
  {
    name: 'Handling Navigation',
    description:'	All about routing and handling navigation',
    dueDate: '2024-06-01',
    priority: 'Low',
  },
];